// WARNING: This file has automatically been generated on Tue, 18 May 2021 20:59:32 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <stdlib.h>
#pragma once

#define __CGOGEN 1

