// WARNING: This file has automatically been generated on Tue, 23 Jun 2020 13:55:01 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package wgh

const (
	// GenlName as defined in wgh/wireguard.h:134
	GenlName = "wireguard"
	// GenlVersion as defined in wgh/wireguard.h:135
	GenlVersion = 1
	// KeyLen as defined in wgh/wireguard.h:137
	KeyLen = 32
	// CmdMax as defined in wgh/wireguard.h:144
	CmdMax = (__CmdMax - 1)
	// DeviceAMax as defined in wgh/wireguard.h:163
	DeviceAMax = (_DeviceALast - 1)
	// PeerAMax as defined in wgh/wireguard.h:186
	PeerAMax = (_PeerALast - 1)
	// AllowedipAMax as defined in wgh/wireguard.h:195
	AllowedipAMax = (_AllowedipALast - 1)
)

// wgCmd as declared in wgh/wireguard.h:139
type wgCmd int32

// wgCmd enumeration from wgh/wireguard.h:139
const (
	CmdGetDevice = iota
	CmdSetDevice = 1
	__CmdMax     = 2
)

// wgdeviceFlag as declared in wgh/wireguard.h:146
type wgdeviceFlag int32

// wgdeviceFlag enumeration from wgh/wireguard.h:146
const (
	DeviceFReplacePeers = uint32(1) << 0
	_DeviceFAll         = DeviceFReplacePeers
)

// wgdeviceAttribute as declared in wgh/wireguard.h:150
type wgdeviceAttribute int32

// wgdeviceAttribute enumeration from wgh/wireguard.h:150
const (
	DeviceAUnspec     = iota
	DeviceAIfindex    = 1
	DeviceAIfname     = 2
	DeviceAPrivateKey = 3
	DeviceAPublicKey  = 4
	DeviceAFlags      = 5
	DeviceAListenPort = 6
	DeviceABindAddr   = 7
	DeviceAFwmark     = 8
	DeviceAPeers      = 9
	_DeviceALast      = 10
)

// wgpeerFlag as declared in wgh/wireguard.h:165
type wgpeerFlag int32

// wgpeerFlag enumeration from wgh/wireguard.h:165
const (
	PeerFRemoveMe          = uint32(1) << 0
	PeerFReplaceAllowedips = uint32(1) << 1
	PeerFUpdateOnly        = uint32(1) << 2
	_PeerFAll              = PeerFRemoveMe | PeerFReplaceAllowedips | PeerFUpdateOnly
)

// wgpeerAttribute as declared in wgh/wireguard.h:172
type wgpeerAttribute int32

// wgpeerAttribute enumeration from wgh/wireguard.h:172
const (
	PeerAUnspec                      = iota
	PeerAPublicKey                   = 1
	PeerAPresharedKey                = 2
	PeerAFlags                       = 3
	PeerAEndpoint                    = 4
	PeerAPersistentKeepaliveInterval = 5
	PeerALastHandshakeTime           = 6
	PeerARxBytes                     = 7
	PeerATxBytes                     = 8
	PeerAAllowedips                  = 9
	PeerAProtocolVersion             = 10
	_PeerALast                       = 11
)

// wgallowedipAttribute as declared in wgh/wireguard.h:188
type wgallowedipAttribute int32

// wgallowedipAttribute enumeration from wgh/wireguard.h:188
const (
	AllowedipAUnspec   = iota
	AllowedipAFamily   = 1
	AllowedipAIpaddr   = 2
	AllowedipACidrMask = 3
	_AllowedipALast    = 4
)
