// WARNING: This file has automatically been generated on Tue, 18 May 2021 20:59:32 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package wgh

/*
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
